version: '3'
services:
  microservice-a:
    build:
      context: ./microservice-a
    ports:
      - "3001:3001"
    networks:
      - microservices_network

  microservice-b:
    build:
      context: ./microservice-b
    ports:
      - "4000:4000"
    networks:
      - microservices_network

networks:
  microservices_network:
